### PR TITLE
Returning a 'Pipeline' from run method of existing examples.

### LINKED ISSUE #241: Example pipelines should return a pipeline with "run" method
This will simplify the integration tests work.

### PR DESCRIPTION
**Pull request by etrain**
Closes #241 

This is in support of making the current PR at amplab/keystone-integration-tests less hacky, and sets a nice foundation for us to continue to test these pipelines in the future.

cc @shivaram @tomerk

### CODE REVIEW

**Comment by shivaram** [comment]
Not a question directly related to this PR, but what can a user do with this returned pipeline ? Can we walk through the nodes and pick things out ? Or is it for applying to test data ?

**Comment by etrain** [comment]
For making predictions.

On Mar 13, 2016, at 6:38 PM, Shivaram Venkataraman <notifications@github.com>
wrote:

Not a question directly related to this PR, but what can a user do with
this returned pipeline ? Can we walk through the nodes and pick things out
? Or is it for applying to test data ?

—
Reply to this email directly or view it on GitHub
<https://github.com/amplab/keystone/pull/248#issuecomment-196099118>.

**Comment by etrain** [comment]
Further, we can .toDotString and look at nodes, for example.

On Mar 13, 2016, at 6:38 PM, Shivaram Venkataraman <notifications@github.com>
wrote:

Not a question directly related to this PR, but what can a user do with
this returned pipeline ? Can we walk through the nodes and pick things out
? Or is it for applying to test data ?

—
Reply to this email directly or view it on GitHub
<https://github.com/amplab/keystone/pull/248#issuecomment-196099118>.

**Comment by shivaram** [comment]
LGTM

**Comment by etrain** [comment]
Ok, merging then..

**Pull request merged**
