### PR TITLE
Replace rowsToMatrix with rowsToMatrixIter

### PR DESCRIPTION
**Pull request by shivaram**
This is safer for handling empty partitions.

cc @ericmjonas @Vaishaal

### CODE REVIEW

**Comment by shivaram** [comment]
Note: I tried to replace all uses of `rowsToMatrix` in `src/main`. The only uses I haven't been able to replace are ones which operate locally (i.e. after sample or collect is called). A full list is pasted below

```
nodes/learning/GaussianMixtureModelEstimator.scala:    val X = MatrixUtils.rowsToMatrix(samples)
nodes/learning/Gradient.scala:      val dataMatrix = MatrixUtils.rowsToMatrix(data)
nodes/learning/Gradient.scala:      val labelsMatrix = MatrixUtils.rowsToMatrix(labels)
nodes/learning/KMeansPlusPlus.scala:    val X = MatrixUtils.rowsToMatrix(data.collect())
nodes/learning/LinearDiscriminantAnalysis.scala:    val featuresByClass = dataAndLabels.groupBy(_._1).values.map(x => MatrixUtils.rowsToMatrix(x.map(_._2)))
nodes/learning/LinearDiscriminantAnalysis.scala:    val features = MatrixUtils.rowsToMatrix(dataAndLabels.map(_._2))
pipelines/images/cifar/RandomPatchCifar.scala:        val baseFilterMat = Stats.normalizeRows(MatrixUtils.rowsToMatrix(baseFilters), 10.0)
```

**Comment by etrain** [comment]
@shivaram There are some merge conflicts here, likely from the cosine random features PR I just merged. Do you mind fixing these? Otherwise this LGTM

**Comment by shivaram** [comment]
Did the merge and fixed it up.

**Comment by etrain** [comment]
Alright, LGTM, merging this.

**Comment by etrain** [comment]
Thanks @shivaram !!

**Pull request merged**
