### PR TITLE
Added seed cosine random features

### PR DESCRIPTION
**Pull request by tomerk**
issue #230 
@Vaishaal

### CODE REVIEW

**Comment by shivaram** [comment]
Can't we just modify the existing RandomCosineFeatures ?

**Comment by tomerk** [comment]
I think it makes sense to have them separate, since it's a tradeoff. Regenerating the whole matrix for each partition (or each single-item apply) instead of serializing and broadcasting it comes with its own different cost.

**Comment by shivaram** [comment]
I'm playing devils advocate here partly, but is there really a trade-off ? i.e. do we have any numbers which show how say as the matrix size, num machines increases the cost of sending data vs. regenerating it changes ?

Because the problem with adding more nodes for each trade-off is that somebody (human or optimizer) needs to choose among them. And I worry without an idea of what is expensive / cheap this won't every be better than trial / error.

**Comment by tomerk** [comment]
That's a fair point, and I don't have any numbers like that for the RDD apply case. (Although trivially if you're looking to do very low-latency single-item applies generating it only once at the start makes much more sense than regenerating it for each item). 

@Vaishaal and @ericmjonas you two seem to be the ones stress-testing cosine random features currently, do you two have any sense of this?

**Comment by Vaishaal** [comment]
So yes I agree with @tomerk that regenerating for every time will be prohibitively expensive. We only generate the kernel matrix from the seed every partition. And number of partitions should be << number of items so it seems like a good tradeoff..

**Comment by etrain** [comment]
I'm a little confused. Do we still even want the seeded one? @shivaram @tomerk

**Comment by shivaram** [comment]
No lets remove the seeded one for now. We'll run regression tests and then add one if we can figure out a regime where its useful

**Comment by tomerk** [comment]
Maybe I should just make a separate PR for the broadcasted cosine random features then? (because this is specifically the seeded random cosines PR) @shivaram @etrain

**Comment by etrain** [comment]
Sure.

**Comment by tomerk** [comment]
See #245

**Comment by etrain** [comment]
Closing this in favor of #245 - if we decide we really want this functionality we can bring it back.

**Pull request closed without merging**
