### PR TITLE
SBT updates for sonatype release

### PR DESCRIPTION
**Pull request by tomerk**
@etrain @shivaram

### CODE REVIEW

**Comment by etrain** [comment]
This looks good to me, but I guess any scripts that rely on the name of the keystone assembly jar will also need to change?

**Comment by tomerk** [comment]
Oh that's true. I've updated the scripts here now, but we probably also need to update the keystone ec2 scripts.

**Comment by shivaram** [comment]
Alright I'm merging this on master branch. @tomerk You can create a branch-0.1 and backport this as we discussed. 

Also I checked the EC2 scripts and they don't actually have the JAR name anywhere so I think they should be fine.

**Comment by tomerk** [comment]
Wait, don't they copy it to all the slaves?



—
Best Wishes,
Tomer Kaftan

**Comment by shivaram** [comment]
They just do `/root/spark-ec2/copy-dir /root/keystone`

**Pull request merged**
