### PR TITLE
add an image crop utility function

### PR DESCRIPTION
**Pull request by stephentu**
Here's a simple function to crop an image into a bounding box. I needed this for feature augmentation, and figured it was useful independently for keystone.

### CODE REVIEW

**Comment by shivaram** [comment]
@etrain Should we make a new node for this ?

**Comment by etrain** [comment]
My thoughts exactly - a "Cropper"? it's implementation can be to call into this function directly.

**Comment by etrain** [comment]
I'm going to go ahead and merge this. I've created #211 to track creation of a `Cropper` but I think this is useful enough on its own.

**Comment by etrain** [comment]
Thanks @stephentu!

**Pull request merged**
